export enum SocketEvent {
  DISCONNECT = "disconnect",
  CONNECTION = "connection",
  JOIN_ROOM = "joinroom",
  ONPLAY = "onplay",
  ONPAUSE = "onpause",
  ONSEEKED = "onseeked",
  SYNCWITHHOST = "syncwithhost",
  HOSTVIDEOSTATE = "hostvideostate",
  NOTIFY = "notify",
  CHATMESSAGE = "chatmessage",
  // Chat-specific events
  JOIN_CHAT_ROOM = "joinChatRoom",
  SEND_CHAT_MESSAGE = "sendChatMessage",
  RECEIVE_CHAT_MESSAGE = "receiveChatMessage",
  USER_TYPING = "userTyping",
  USER_STOPPED_TYPING = "userStoppedTyping",
  LEAVE_CHAT_ROOM = "leaveChatRoom",
  GET_CHAT_HISTORY = "getChatHistory",
  // MediaSoup events
  CONNECT_TRANSPORT = "connectTransport",
  PRODUCE = "produce",
  CONSUME = "consume",
  LEAVE_ROOM = "leaveRoom",
  UNPAUSE_CONSUMERS = "unpauseConsumers",
  INCOMING_PRODUCER = "incomingProducer",
}
